name: AutomatedWorkflow

on:
  push:
    branches:
      - main

jobs:
  integration-delivery:
    runs-on: ubuntu-latest
    environment: Test
    container:
      image: node
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: .

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

